<div id='left'>
    <div class='row1'>
        <h2>Wanted</h2>
        <p><b>We are looking for skills in:</b></p>
        <ul>
            <li>Skill 01</li>
            <li>Skill 02</li>
            <li>Skill 03</li>
            <li>Skill 04</li>
            <li>Skill 05</li>
        </ul>
    </div>
</div>
<div id='right'>
    <div class='row1'>
        <h2>Career</h2>
        <p>
            <b>Would you like to be a part of the dynamic company?<b>
        </p>
        <p>
            Please send us your CV at
            <a href="mailto:career@crownemc.com">career@crownemc.com</a> and we
            will contact you for any open positions that suit your area of
            expertise.
        </p>
    </div>
</div>
