<div id='left'>
    <div class='row1'>
        <h2>Contact Us</h2>

        <b>Address</b><br />
        <div>
            Sciecaturpis rasamet<br />
            Arcuolor met nsectetuer<br />
            Lerosertas fertase<br />
            Delerats maisrtay
        </div>

        <b>Phone</b><br />
        <div>
            1234567890<br />
            1234567890<br />
            1234567890
        </div>

        <b>Fax</b><br />
        <div>
            1234567890<br />
            1234567890
        </div>

        <b>Email</b><br />
        <div>
            <a href='info@crownemc.com'>info@crownemc.com</a>
        </div>
    </div>
</div>
<div id='right'>
    <div class='row1'>
        <h2>Send Message</h2>
        <form action='' method='post'>
            <p>
                <label for='name'>Name</label>
                <input type='text' name='name' id='name' class='text' />
            </p>
            <p>
                <label for='organisation'>Organisation</label>
                <input type='text' name='organisation' id='organisation'
                  class='text' />
            </p>
            <p>
                <label for='telephone'>Telephone</label>
                <input type='text' name='telephone' id='telephone'
                  class='text' />
            </p>
            <p>
                <label for='fax'>Fax</label>
                <input type='text' name='fax' id='fax' class='text' />
            </p>
            <p>
                <label for='e-mail'>E-mail</label>
                <input type='text' name='e-mail' id='e-mail' class='text' />
            </p>
            <p>
                <label for='message'>Message</label>
                <textarea name='message' id='message'></textarea>
            </p>
            <p>
                <input type='submit' name='submit' value='Send Message' />
                <input type='reset'  name='reset'  value='Reset' />
            </p>
        </form>
    </div>
</div>
