<div id='left'>
    <div class='row1'>
        <h2>Projects</h2>
        <ul>
            <li>taserto yasers mertase</li>
            <li>kersade delertsde miaserder resertase</li>
            <li>taserto yasertase</li>
            <li>dolor sit avertaero kertase</li>
            <li>taserto yasers mertase</li>
            <li>kersade delertsde miaserder resertase</li>
            <li>taserto yaasertase</li>
        </ul>
        <a class='button' href='#'>➤ Read More</a>
    </div>
    <div class='row2'>
        <h2>Primary Contacts</h2>
        <p>11 Some Street Second Floor<br />
        New York WA 02020<br />
        Tel/Fax: 222-1111, 111-1111</p>
        <a class='button' href='#'>➤ Send Message</a>
    </div>
</div>
<div id='right'>
    <div class='row1'>
        <h2>Welcome</h2>
        <p><b>Ipsum dolorsit ametct tueradi keroderase lerofe
        delaserta</b><br />Sciecaturpis rasamet arcuolor met
        nsectetuer lerosertas fertase delerats maisrtays ra
        neque feugi dolorolor sit amet consetuer adipi seadre
        kerofe delertas niaseras kerofe miase viverra neque
        feugiatolot consequaplacerat.</p>
        <a class='button' href='#'>➤ Read More</a>
    </div>
    <div class='row2'>
        <h2>Our Services</h2>
        <img src='statics/images/helmet.jpg' alt='Helmet' />
        <p><b>Ipsum dolorsit ametct tueradi keroderase lerofe
        delaserta</b><br />Sciecaturpis rasamet arcuolor met
        nsectetuer lerosertas fertase delerats maisrtays ra
        neque feugi dolorolor sit amet consetuer adipi seadre
        kerofe delertas niaseras kerofe miase viverra neque
        feugiatolot consequaplacerat.</p>
        <a class='button' href='#'>➤ Read More</a>
    </div>
</div>
