<div id='left'>
    <div class='row1'>
        <h2>Projects</h2>
        <ul>
            <li>Project 01</li>
            <li>Project 02</li>
            <li>Project 03</li>
            <li>Project 04</li>
            <li>Project 05</li>
            <li>Project 06</li>
            <li>Project 07</li>
        </ul>
        <a class='button' href='index.php?page=projects'>➤ Read More</a>
    </div>
    <div class='row2'>
        <h2>Primary Contacts</h2>
        <p>
            11 Some Street Second Floor<br />
            New York WA 02020<br />
            Tel/Fax: 222-1111, 111-1111
        </p>
        <a class='button' href='index.php?page=contact'>➤ Send Message</a>
    </div>
</div>
<div id='right'>
    <div class='row1'>
        <h2>Welcome</h2>
        <p>
            <b>We, the Crown ElectroMechanical Cont, are proud to be a leader in
            the fields of electrical, plumbing, fire fighting and
            airconditioning.</b>
        </p>
        <p>
            Since our establishment, we have built our reputation on outstanding
            quality and timely project delivery. We have the resources and
            experience to meet the needs of a wide variety of clients.
        </p>
        <p>
            We give  the company’s management and technical resources to all our
            projects, providing our clients with full-scale solutions. Our
            designers, engineers, construction and installation teams are
            supported by a complete materials handling and delivery team. This
            ensures that the projects  are on time, as needed.
        </p>
    </div>
    <div class='row2'>
        <h2>Our Services</h2>
        <img src='statics/images/helmet.png' alt='Helmet' />
        <p>
            <b>In general Complete Mechanical, Electrical & Plumbing works for
            all your needs.</b>
        </p>
        <p>
            Turnkey contracts in electromechanical works, including detailed
            system engineering, selection and supply of equipment, erection,
            installation, duct fabrication and installation, insulation etc.
        </p>
    </div>
</div>
