<div id='left'>
    <div class='row1'>
        <h2>Services List</h2>
        <p><b>Our main services in MEP contracting include</b></p>
        <ul>
            <li>Erection of ducted split units and its duct works.</li>
            <li>Installation and maintenance of Air-conditioning.</li>
            <li>
                Annual maintenance contract for complete a/c units, fresh air
                units air curtains and kitchen equipments.
            </li>
            <li>
                Electrical contracting which includes industrial, commercial and
                residential.
            </li>
            <li>
                Electrical works,equipment fitting , cable laying, extention and
                maintenance.
            </li>
            <li>
                Installation of electrical light poles, lights and underground
                cable laying.
            </li>
            <li>
                Fire fighting and Fire-alarms and security systems, and other
                allied electromechanical works.
            </li>
            <li>Refurbishing and upgrading of existing MEP systems.</li>
            <li>Refrigeration works.</li>
            <li>Plumbing ,underground pipe lin works & drainage.</li>
        </ul>
    </div>
</div>
<div id='right'>
    <div class='row1'>
        <h2>Services Overview</h2>
        <p>
            <b>Ipsum dolorsit ametct tueradi keroderase lerofe delaserta</b>
        </p>
        <p>
            Sciecaturpis rasamet arcuolor met nsectetuer lerosertas fertase
            delerats maisrtays ra neque feugi dolorolor sit amet consetuer adipi
            seadre kerofe delertas niaseras kerofe miase viverra neque
            feugiatolot consequaplacerat.
        </p>
        <p>
            <b>Ipsum dolorsit ametct tueradi keroderase lerofe delaserta</b>
        </p>
        <p>
            Sciecaturpis rasamet arcuolor met nsectetuer lerosertas fertase
            delerats maisrtays ra neque feugi dolorolor sit amet consetuer adipi
            seadre kerofe delertas niaseras kerofe miase viverra neque
            feugiatolot consequaplacerat.
        </p>
    </div>
</div>
