<tt>
    <a href="index.php?page=home">Home</a> |
    <a href="index.php?page=about_us">About us</a> |
    <a href="index.php?page=projects">Projects</a> |
    <a href="index.php?page=services">Services</a> |
    <a href="index.php?page=career">Career</a> |
    <a href="index.php?page=contact_us">Contact us</a>
</tt>

<br />

<tt>Designed and developed by <a href="http://cubegin.com/"
  title="CubeGin">CubeGin</a> &copy; 2009</tt>
