<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
  codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0"
  width="950" height="425">
    <param name="movie"
      value="statics/flash/header.swf?image=statics/images/<?php echo $page ?>.jpg">
    <param name="quality" value="high">
    <embed
      src="statics/flash/header.swf?image=statics/images/<?php echo $page ?>.jpg"
      quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer"
      type="application/x-shockwave-flash" width="950" height="425"></embed>
</object>
